practice/urls.py
from django.urls import path
from . import views

app_name = 'practice'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:quiz_id>/calificar/', views.calificar, name='calificar'),
  path('<int:quiz_id>/', views.quiz_view, name='quiz_view'),
]

practice/models.py
from django.db import models

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=200)

    def __str__(self):
        return self.texto_pregunta

class Quiz(models.Model):
    tema = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=300, default="Resuelve los ejercicios")
    fecha_creacion = models.DateTimeField('fecha de creacion', auto_now_add=True)
    fecha_actualizacion = models.DateTimeField('fecha de actualizacion', auto_now=True)
    preguntas = models.ManyToManyField(Pregunta)

    class Meta:
        ordering: ('tema')

    def __str__(self):
        return self.tema

class Opcion(models.Model):
    texto_opcion = models.CharField(max_length=200)
    verdadero = models.BooleanField(default=False)
    pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)

    def __str__(self):
        if self.verdadero:
            validez = "verdadero"
        else:
            validez = "falso"
        return f"{self.texto_opcion} es {validez}"

practice/views.py
import json

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Quiz, Pregunta, Opcion

def index(request):
    quizzes = Quiz.objects.all()
    return render(request, 'practice/index.html', {'quizzes': quizzes})

def quiz_view(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(request, 'practice/quiz_view.html', {'quiz': quiz, "disable": False})

def calificar(request, quiz_id):
    quiz = Quiz.objects.get(pk=quiz_id)
    opciones = [request.POST[elem] for elem in request.POST if elem.startswith('opcion')]
    lista = []
    if opciones:
        lista = [Opcion.objects.get(pk=elem).verdadero for elem in opciones]
    answers = {key: value for key, value in zip(opciones, map(lambda x: 1 if x else 0, lista))}
    return render(request, 'practice/quiz_view.html', {'quiz': quiz, 'disable': True, "respuestas": answers, "opciones": opciones})

practice/templates/practice/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Ejercicios para mejorar la gramática y vocabulario en inglés">
    <meta name="author" content="Leonardo Martinez">
    {% block title %}<title>Ejercicios de inglés</title>{% endblock %}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static "practice/album.css" %}" rel="stylesheet">
  </head>
  <body>
    <header>
  <div class="collapse navbar-bgcolor" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Acerca</h4>
          <p class="text-muted">Página para practicar inglés por medio de ejercicios de gramática y vocabulario.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contacto</h4>
          <ul class="list-unstyled">
            <li><a href="https://twitter.com/pythonista100" class="text-white">Twitter</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark navbar-bgcolor shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="{% url 'practice:index' %}" class="navbar-brand d-flex align-items-center">
        <i class="fas fa-chalkboard-teacher" style="margin-right: 12px;"></i>
        <strong>English Tutor</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>
  {% block content %}

  {% endblock %}
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>

    </p>
  </div>
</footer>
{{ respuestas|json_script:"respuestas" }}
<script>
</script>
<script src="{% static 'practice/js/main.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://getbootstrap.com/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
</body>
</html>

practice/templates/practice/index.html
{% extends "practice/base.html" %}

{% block content %}

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">English Exercises</h1>
    </div>

  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

        {% for quiz in quizzes %}
        
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <a href="{% url 'practice:quiz_view' quiz.id %}"><svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#20639B"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ quiz.tema }}</text></svg></a>
            <div class="card-body">
              <p class="card-text">{{ quiz.descripcion }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'practice:quiz_view' quiz.id %}"><button type="button" class="btn btn-sm btn-outline-secondary">Ver</button></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>

</main>

{% endblock %}

practice/templates/practice/quiz_view.html
{% extends "practice/base.html" %}

{% block content %}
<div class="container">

<div class="col-md-6 quiz-area">
  <h1>{{ quiz.tema }}</h1>
  <form action="{% url 'practice:calificar' quiz.id %}" method="post">
  {% csrf_token %}
  {% for pregunta in quiz.preguntas.all %}
      <p>{{ forloop.counter }}. {{pregunta}}</p>
      <ul>
      {% for opcion in pregunta.opcion_set.all %}
          <div class="form-check">
            <input class="form-check-input" type="radio" name="opcion{{forloop.parentloop.counter}}" id="{{ opcion.id }}" value="{{opcion.id}}" {% if disable %}disabled{% endif %}>
            <label class="form-check-label" for"opcion{{ forloop.counter }}">{{ opcion.texto_opcion }}</label>
          </div>
      {% endfor %}
      </ul>
  {% endfor %}
  <input id="button-submit" class="btn btn-success" type="submit" value="calificar" {% if disable %}disabled{% endif %}>
  </form>
  {% if respuesta %}{{respuesta}}{% endif %}
  {% if disable %}
  <a href="{% url 'practice:quiz_view' quiz.id %}">Repetir quiz?</a>
  {% endif %}
</div>

</div><!-- Container  -->
{% endblock %}

practice/templates/practice/test1.html
{% extends "cuestionario/base.html" %}

<h1>{{ quiz.tema }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'cuestionario:calificar' quiz.id %}" method="post">
{% csrf_token %}
{% for pregunta in quiz.preguntas.all %}
    <p>{{ pregunta.texto_pregunta }}</p>
    {% for opcion in pregunta.opcion_set.all %}
        <input type="radio" name="opcion" id="opcion{{ forloop.counter }}" value="{{ opcion.id }}">
        <label for="opcion{{ forloop.counter }}">{{ opcion.texto_opcion }}</label><br>
    {% endfor %}
{% endfor %}
<input type="submit" value="Calificar">
</form>